- name: Create a folder in jenkins
  community.general.jenkins_job:
    config: "{{ lookup('template', 'folder.xml') }}"
    name: "{{item.name}}"
    token: 1148851f926ee7e37aba7af72124c75432
    url: http://jenkins.devops65.online:8080
    user: admin
  loop: "{{folder}}"

- name: Create a jenkins multibranch pipeline job using the token
  community.general.jenkins_job:
    config: "{{ lookup('template', 'multibranch.xml') }}"
    name: "{{item.folderName}}{{item.jobName}}"
    token: 1148851f926ee7e37aba7af72124c75432
    url: http://jenkins.devops65.online:8080
    user: admin
  loop: "{{multibranchJobs}}"


#- name: Create a jenkins single pipeline job using the token
#  community.general.jenkins_job:
#    config: "{{ lookup('template', 'pipe1.xml') }}"
#    name: "{{item.folderName}}{{item.jobName}}"
#    token: 1148851f926ee7e37aba7af72124c75432
#    url: http://jenkins.devops65.online:8080
#    user: admin
#  loop: "{{pipelineJobs}}"





