- name: Create a folder in jenkins
  community.general.jenkins_job:
    config: "{{ lookup('template', 'folder.xml') }}"
    name: "{{item.name}}"
    token: 11c290492f2b0966e6549471b763a1cdf7
    url: http://jenkins.devops65.online:8080
    user: admin
  loop: "{{folder}}"

- name: Create a jenkins multibranch pipeline job using the token
  community.general.jenkins_job:
    config: "{{ lookup('template', 'multibranch.xml') }}"
    name: "{{item.folderName}}{{item.jobName}}"
    token: 11c290492f2b0966e6549471b763a1cdf7
    url: http://jenkins.devops65.online:8080
    user: admin
  loop: "{{multibranchJobs}}"


#- name: Create a jenkins single pipeline job using the token
#  community.general.jenkins_job:
#    config: "{{ lookup('template', 'pipe.xml') }}"
#    name: "{{item.folderName}}{{item.jobName}}"
#    token: 113d48cab5b9336bc3a1fe9de40d67323c
#    url: http://jenkins.devops65.online:8080
#    user: admin
#  loop: "{{pipelineJobs}}"





