- name: Create a jenkins folder using the token
  community.general.jenkins_job:
    config: "{{ lookup('template', 'folder.xml') }}"
    name: "{{item.folderName}}"
    token: 11c8db34e2bf8e52a29005cc703403744e
    url: http://jenkins.devops65.online:8080
    user: admin
  loop:
    - { folderName: "CI-pipeline-jobs ", description: "This is a folder for CI-pipeline jobs" }


- name: Create a jenkins job using the token
  community.general.jenkins_job:
    config: "{{ lookup('template', 'pipe.xml') }}"
    name: "{{item.jobName}}"
    token: 11c8db34e2bf8e52a29005cc703403744e
    url: http://jenkins.devops65.online:8080
    user: admin
  loop:
    - { jobName: "cart", componentName: "cart", repoName: "cart" }





