- name: copy a file
  ansible.builtin.template:
    src: pipe.xml
    dest: /tmp/pipe.xml
  loop:
    - {componentName: "cart", repoName: "cart"}


- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', 'tmp/pipe.xml') }}"
    name: Srinivas
    password: Jenkins
    url: http://jenkins.devops65.online:8080
    user: admin






#- name: Create a jenkins job using the username and password
#  community.general.jenkins_job:
#    config: "{{ lookup('template', 'templates/pipe.xml') }}"
#    name: Srinivas
#    url: http://jenkins.devops65.online:8080
#    user: admin
#    password: Jenkins
#  loop:
#    - {componentName: "cart" , repoName: "cart" }